import { TParameters } from 'src/app/core/parameters/parameters.interface';
import { BigNumber } from 'src/app/core/models/big-number/big-number.model';

export const PARAMETERS_START_CONFIG: TParameters = {
  clickButtonText: {
    name: '',
    isVisible: false,
    value: 'Click me!',
    isPercent: false,
    isResetOnPrestige: false,
  },

  baseMoneyRate: {
    name: '',
    isVisible: false,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  baseCrystalRate: {
    name: '',
    isVisible: false,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  baseCrystalChanceRate: {
    name: '',
    isVisible: false,
    value: 1,
    isPercent: false,
    isResetOnPrestige: false,
  },
  basePrestigeRate: {
    name: '',
    isVisible: false,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  baseRubyRate: {
    name: '',
    isVisible: false,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  baseRubyChanceRate: {
    name: '',
    isVisible: false,
    value: 1,
    isPercent: false,
    isResetOnPrestige: false,
  },

  flatBonus: {
    name: 'Flat bonus',
    isVisible: true,
    value: new BigNumber(0),
    isPercent: false,
    isResetOnPrestige: true,
  },
  flatBonusUpgrade1: {
    name: '',
    isVisible: false,
    value: new BigNumber(1000000),
    isPercent: false,
    isResetOnPrestige: true,
  },
  flatBonusUpgradePrestige: {
    name: '',
    isVisible: false,
    value: new BigNumber(10),
    isPercent: false,
    isResetOnPrestige: false,
  },
  flatBonusStart: {
    name: 'Start flat bonus',
    isVisible: true,
    value: new BigNumber(0),
    isPercent: false,
    isResetOnPrestige: false,
  },
  flatBonusStartCoefficient: {
    name: '',
    isVisible: false,
    value: new BigNumber(100),
    isPercent: false,
    isResetOnPrestige: false,
  },

  simpleMultiplier: {
    name: 'Simple multiplier',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: true,
  },
  simpleMultiplierIncrease: {
    name: '',
    isVisible: false,
    value: new BigNumber(2),
    isPercent: false,
    isResetOnPrestige: true,
  },
  simpleMultiplierCoefficient: {
    name: 'Simple multiplier coefficient',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: true,
  },
  simpleMultiplierCoefficientIncrease: {
    name: '',
    isVisible: false,
    value: new BigNumber(3),
    isPercent: false,
    isResetOnPrestige: true,
  },
  simpleMultiplierBuyBonus: {
    name: '',
    isVisible: false,
    value: new BigNumber(0.1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  simpleMultiplierPower: {
    name: 'Simple multiplier power',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  simpleMultiplierPowerCoefficient: {
    name: '',
    isVisible: false,
    value: new BigNumber(0.1),
    isPercent: false,
    isResetOnPrestige: false,
  },

  permanentSimpleMultiplier: {
    name: 'Permanent simple multiplier',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  permanentSimpleMultiplierCoefficient: {
    name: '',
    isVisible: false,
    value: new BigNumber(1.1),
    isPercent: false,
    isResetOnPrestige: false,
  },

  crystalChance: {
    name: 'Crystal chance',
    isVisible: true,
    value: 200,
    isPercent: true,
    isResetOnPrestige: true,
  },
  crystalChanceIncrease: {
    name: '',
    isVisible: false,
    value: 20,
    isPercent: true,
    isResetOnPrestige: true,
  },
  crystalChanceMoneyIncrease: {
    name: '',
    isVisible: false,
    value: 10,
    isPercent: true,
    isResetOnPrestige: true,
  },
  crystalChanceOnPrestige: {
    name: 'Crystal chance from all prestige',
    isVisible: true,
    value: 0,
    isPercent: true,
    isResetOnPrestige: false,
  },
  crystalChanceOnPrestigeCoefficient: {
    name: 'Crystal chance on prestige',
    isVisible: false,
    value: 100,
    isPercent: true,
    isResetOnPrestige: false,
  },
  crystalChanceOnPrestigeCoefficientIncrease: {
    name: '',
    isVisible: false,
    value: 100,
    isPercent: true,
    isResetOnPrestige: false,
  },
  crystalChanceByPrestige: {
    name: 'Crystal chance by prestige points',
    isVisible: true,
    value: 0,
    isPercent: true,
    isResetOnPrestige: false,
  },
  crystalChanceByPrestigeCoefficient: {
    name: '',
    isVisible: false,
    value: 100,
    isPercent: true,
    isResetOnPrestige: false,
  },
  crystalMultiplier: {
    name: 'Crystal multiplier',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: true,
  },
  crystalMultiplierCoefficient: {
    name: 'Crystal multiplier coefficient',
    isVisible: true,
    value: new BigNumber(2),
    isPercent: false,
    isResetOnPrestige: true,
  },
  crystalMultiplierCoefficientIncrease: {
    name: '',
    isVisible: false,
    value: new BigNumber(0.1),
    isPercent: false,
    isResetOnPrestige: true,
  },
  crystalGainMultiplier: {
    name: 'Crystal gain multiplier',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },

  rubyChance: {
    name: 'Ruby chance',
    isVisible: true,
    value: 10,
    isPercent: true,
    isResetOnPrestige: false,
  },
  rubyChanceCoefficient: {
    name: '',
    isVisible: false,
    value: 2,
    isPercent: true,
    isResetOnPrestige: false,
  },
  rubyCristalGainMultiplier: {
    name: '',
    isVisible: false,
    value: new BigNumber(2),
    isPercent: false,
    isResetOnPrestige: true,
  },

  logMultiplierBase: {
    name: 'Logarithm multiplier base',
    isVisible: true,
    value: 1000,
    isPercent: false,
    isResetOnPrestige: true,
  },
  logMultiplierBaseDecrease: {
    name: '',
    isVisible: false,
    value: 1.75,
    isPercent: false,
    isResetOnPrestige: true,
  },
  logMultiplierPower: {
    name: 'Logarithm multiplier power',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: true,
  },
  logMultiplierPowerIncrease: {
    name: '',
    isVisible: false,
    value: new BigNumber(0.25),
    isPercent: false,
    isResetOnPrestige: true,
  },

  prestigeBorder: {
    name: 'Current prestige border',
    isVisible: true,
    value: new BigNumber(100000000),
    isPercent: false,
    isResetOnPrestige: true,
  },
  prestigeBorderGrowth: {
    name: 'Prestige border power coefficient',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  prestigeBorderGrowthCoefficient: {
    name: '',
    isVisible: false,
    value: new BigNumber(1.4),
    isPercent: false,
    isResetOnPrestige: false,
  },
  prestigeBorderDecrease: {
    name: 'Prestige border decreasing',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: true,
  },
  prestigeBorderDecreaseCoefficient: {
    name: '',
    isVisible: false,
    value: new BigNumber(1.1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  prestigePointsGainPower: {
    name: 'Prestige point gain coefficient',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  prestigePointsGainPowerCoefficient: {
    name: '',
    isVisible: false,
    value: new BigNumber(0.1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  prestigeMultiplier: {
    name: 'Prestige multiplier',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  prestigeMultiplierCoefficient: {
    name: '',
    isVisible: false,
    value: new BigNumber(5),
    isPercent: false,
    isResetOnPrestige: false,
  },

  oneTimeMultiplier: {
    name: 'Another multiplier',
    isVisible: true,
    value: new BigNumber(1),
    isPercent: false,
    isResetOnPrestige: false,
  },
  oneTimeMultiplierBonus1: {
    name: '',
    isVisible: false,
    value: new BigNumber(50),
    isPercent: false,
    isResetOnPrestige: false,
  },
};
