export enum EUnlocks {
  CRYSTALS = 'CRYSTALS',
  PRESTIGE = 'PRESTIGE',
  RUBIES = 'RUBIES',
  LOG_MULTIPLIER = 'LOG_MULTIPLIER',
  SETTINGS_AND_ABOUT = 'SETTINGS_AND_ABOUT',
  MORE_UPGRADES_1 = 'MORE_UPGRADES_1',
  FLAT_BONUS_1 = 'FLAT_BONUS_1',
}
