export enum EUnlocks {
  CRYSTALS = 'CRYSTALS',
  PRESTIGE = 'PRESTIGE',
  RUBY = 'RUBY',
  LOG_MULTIPLIER = 'LOG_MULTIPLIER',
  SETTINGS_AND_ABOUT = 'SETTINGS_AND_ABOUT',
  MORE_UPGRADES_1 = 'MORE_UPGRADES_1',
  FLAT_BONUS_1 = 'FLAT_BONUS_1',
  RUBY_BASED_MULTIPLIER = 'RUBY_BASED_MULTIPLIER',
  PERMANENT_SIMPLE_MULTIPLIER = 'PERMANENT_SIMPLE_MULTIPLIER',
  SIMPLE_MULTIPLIER_BUY_BONUS = 'SIMPLE_MULTIPLIER_BUY_BONUS',
}
