export enum EUpgradeBuyType {
  ENDLESS = 'ENDLESS',
  WITH_COUNT = 'WITH_COUNT',
  ONE_TIME = 'ONE_TIME',
}

export enum EUpgradeType {
  MONEY = 'MONEY',
  CRYSTAL = 'CRYSTAL',
  RUBY = 'RUBY',
  PRESTIGE = 'PRESTIGE',
}

export enum EUpgradeCostGrowth {
  NONE = 'NONE',
  PLUS = 'PLUS',
  PLUS_BY_COUNT = 'PLUS_BY_COUNT',
  MULTIPLY = 'MULTIPLY',
  MULTIPLY_BY_COUNT = 'MULTIPLY_BY_COUNT',
  POWER = 'POWER',
}

export enum EUpgradeTier {
  COMMON = 'var(--upgrade-common-color)',
  UNCOMMON = 'var(--upgrade-uncommon-color)',
  UNIQUE = 'var(--upgrade-unique-color)',
  RARE = 'var(--upgrade-rare-color)',
  EPIC = 'var(--upgrade-epic-color)',
  LEGENDARY = 'var(--upgrade-legendary-color)',
  MYTHIC = 'var(--upgrade-mythic-color)',
}

export enum EUpgrades {
  SIMPLE_MULTIPLIER = 'SIMPLE_MULTIPLIER',
  SIMPLE_MULTIPLIER_BOOST = 'SIMPLE_MULTIPLIER_BOOST',
  CRYSTAL_CHANCE = 'CRYSTAL_CHANCE',
  CRYSTAL_MULTIPLIER = 'CRYSTAL_MULTIPLIER',
  LOG_MULTIPLIER_BASE = 'LOG_MULTIPLIER_BASE',
  SIMPLE_MULTIPLIER_POWER = 'SIMPLE_MULTIPLIER_POWER',
  PRESTIGE_MULTIPLIER = 'PRESTIGE_MULTIPLIER',
  CRYSTAL_MULTIPLIER_COEFFICIENT = 'CRYSTAL_MULTIPLIER_COEFFICIENT',

  LOG_MULTIPLIER_POWER = 'LOG_MULTIPLIER_POWER',
  CRYSTAL_CHANCE_BY_MONEY = 'CRYSTAL_CHANCE_BY_MONEY',
  START_FLAT_BONUS = 'START_FLAT_BONUS',

  UNLOCK_CRYSTALS = 'UNLOCK_CRYSTALS',
  UNLOCK_SETTINGS_AND_ABOUT = 'UNLOCK_SETTINGS_AND_ABOUT',
  UNLOCK_PRESTIGE = 'UNLOCK_PRESTIGE',
  UNLOCK_LOG_MULTIPLIER = 'UNLOCK_LOG_MULTIPLIER',
  UNLOCK_RUBIES = 'UNLOCK_RUBIES',
  FLAT_BONUS = 'FLAT_BONUS',
  CRYSTAL_CHANCE_ON_PRESTIGE = 'CRYSTAL_CHANCE_ON_PRESTIGE',
  MULTIPLY_CRYSTAL_GAIN = 'MULTIPLY_CRYSTAL_GAIN',
}
